apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
    type: database
  name: mariadb-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
    type: database
  type: ClusterIP

