apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    type: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
        - name: 'mydb'
          image: mariadb:10.3
          ports:
          - containerPort: 3306
            name: db-port
          expose: 
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "12345"
          - name: MYSQL_USER
            value: "ovidiu"
          - name: MYSQL_PASSWORD
            value: "12345"
          - name: MYSQL_DATABASE
            value: "myDB"
          volumeMounts:
          - name: volume-db
            mountPath: /var/lib/mysql
      volumes:
        - name: volume-db
          hostPath:
            path: /home