apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  creationTimestamp: null
  generation: 1
  name: diz-app-deploy
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/diz-app-deploy
spec:
  rules:
  - host: diz-app-deploy.5e13843ce816477ea577.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: diz-app-deploy
          servicePort: 80
        path: /
status:
  loadBalancer: {}
